title: "AimaCity - 爱码学城"
subtitle: "爱码学城 - 有趣的成长、分享、探索社区"
description: "爱码学城是一个有趣的成长、分享、探索社区，小伙伴们一起加入吧"
author: AimaCity
language: zh-cn
timezone: Asia/Shanghai

url: https://aima.city
root: /
permalink: growth/:year/:month/:day/:title/
archive_dir: growth
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
#deploy:
#  type: git
#  repo: https://github.com/aimacity/aimacity.github.io.git

deploy:
  type: sftp
  host: aima.city
  user: ec2-user
#  pass: <password>
  remotePath: /home/wwwroot/aima.city
  port: 22
  privateKey: /media/software/workspace/aws

highlight:
  enable: true
  line_number: false

disqus_shortname: aimacity
google_analytics: UA-125328384-1
growingio: a0cbd0ba38735eb1
baidu: c6bfc33e69eb85228859af04b50b8805
fb_admins: 100000247608790
algolia:
  en:
    api_key: 23881a7e25879a2bed42c77ec5487363
    index_name: aimacity
  zh-cn:
    api_key: 23881a7e25879a2bed42c77ec5487363
    index_name: aimacity
twitter: wangzhihu
github: aimacity
qiniu:
  offline: false
  sync: true
  bucket: aimacity
  secret_file: /media/software/workspace/qiniu.json
  access_key: AccessKey
  secret_key: SecretKey
  dirPrefix: static
  urlPrefix: http://pokmk0bdn.bkt.clouddn.com/static
  up_host: https://upload-z0.qiniup.com
  local_dir: source
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css
